O1006 (FRESADO DE ROSCAS RH - CLIMB MILLING CCW)

(========================================)
(--- VARIABLES DE ENTRADA DEL OPERARIO ---)
#20 = 1     (NUMERO DE HERRAMIENTA)
(========================================)
#1 = 64.0   (DIAMETRO NOMINAL FIN DE LA ROSCA)
#2 = 20.0   (DIAMETRO DE LA FRESA DE ROSCAR)
#3 = 30.0   (PROFUNDIDAD TOTAL DE LA ROSCA - Z FINAL POSITIVO)
#4 = 2.0    (PASO DE LA ROSCA / PITCH - EJ: 2.0mm)
#5 = 1.0    (NUMERO DE VUELTAS: 1=FRESA MULTIPASO, VARIAS=FRESA UN FILO)
#6 = 120.0  (Vc - VELOCIDAD DE CORTE EN m/min)
#7 = 4.0    (NUMERO DE INSERTOS O LABIOS)
#8 = 0.05   (fz - AVANCE POR INSERTO EN mm/rev)
#9 = 50.0   (PLANO DE SEGURIDAD RETROCESO R)
#10 = 0.0   (COORDENADA X DEL CENTRO DEL AGUJERO)
#11 = 0.0   (COORDENADA Y DEL CENTRO DEL AGUJERO)
(========================================)

(--- COMPROBACIONES DE SEGURIDAD BASICAS ---)
IF [#2 GE #1] GOTO 9001
IF [#4 LE 0] GOTO 9002
IF [#5 LT 1.0] GOTO 9003

(--- CALCULOS DE PARAMETROS DE CORTE ---)
#100 = ROUND[[#6 * 1000] / [3.1416 * #2]] (CALCULO DE RPM)
#101 = ROUND[#100 * #7 * #8] (AVANCE LINEAL NOMINAL F)

(--- CALCULOS GEOMETRICOS DE LA TRAYECTORIA ---)
#102 = [#1 - #2] / 2 (RADIO EFECTIVO DE LA TRAYECTORIA DEL CENTRO HTA)
#103 = #102 / 2 (RADIO DE LOS ARCOS DE ENTRADA Y SALIDA TANGENCIAL)

(--- CALCULO DE AVANCE COMPENSADO PARA INTERPOLACION CIRCULAR INTERNA ---)
#106 = ROUND[#101 * #102 / [#1 / 2]] 

(--- DEFINICION DE COORDENADAS Z ---)
#104 = -#3 (Z FINAL ABSOLUTO EN EL FONDO DE LA ROSCA)
#105 = #4 / 2 (ASCENSO EN Z DURANTE LA MEDIA VUELTA DE ENTRADA/SALIDA)

(--- ENCABEZADO DE MAQUINA Y POSICIONAMIENTO ---)
T#20 M06 (LLAMAR HERRAMIENTA)
G90 G54 G17 G40 G80 G49
G00 X#10 Y#11 (POSICIONAMIENTO EN EL CENTRO EXACTO DEL AGUJERO)
G43 H#20 Z#9 (*** VERIFICAR CORRECTOR DE ALTURA H ***)
S#100 M03
M08

(--- ACERCAMIENTO RAPIDO ---)
G00 Z2.0 (ACERCAMIENTO HASTA 2MM POR ENCIMA DEL MATERIAL)
G01 Z#104 F[#101 / 2] (BAJADA CONTROLADA POR EL CENTRO HASTA EL FONDO)

(========================================)
(       RUTINA HELICOIDAL DE ROSCADO     )
(========================================)

(--- ARCO TANGENCIAL DE ENTRADA DE 180 GRADOS ---)
G03 X[#10 + #102] Y#11 Z[#104 + #105] I[#103] J0. F#106

(--- INICIALIZACION DEL BUCLE ---)
#110 = 0 (CONTADOR DE VUELTAS)
#111 = #104 + #105 (COORDENADA Z ACTUAL DESPUES DE LA ENTRADA)

N100 (--- BUCLE HELICOIDAL PRINCIPAL ---)
IF [#110 GE #5] GOTO 200 (SI COMPLETO LAS VUELTAS, SALTA A LA SALIDA)
#111 = #111 + #4 (CALCULA EL Z PARA LA SIGUIENTE VUELTA SUMANDO UN PASO)

(INTERPOLACION HELICOIDAL DE 360 GRADOS)
G03 X[#10 + #102] Y#11 Z#111 I-[#102] J0. F#106

#110 = #110 + 1 (INCREMENTA EL CONTADOR)
GOTO 100 (REPITE EL BUCLE)

N200 (--- FIN DEL BUCLE HELICOIDAL ---)

(--- ARCO TANGENCIAL DE SALIDA DE 180 GRADOS ---)
#111 = #111 + #105 (CALCULA EL ASCENSO Z PARA LA SALIDA TANGENCIAL)
G03 X#10 Y#11 Z#111 I-[#103] J0. F#106

(*** CINEMATICA SEGURA EXCLUSIVA PARA ROSCADOS ***)
(A diferencia de las cajeras de desbaste, en una rosca la herramienta DEBE)
(estar en el centro geográfico X#10 Y#11 antes de levantar el eje Z.)
(Si el Z subiera estando en el diámetro efectivo, arrancaría los hilos de la pieza.)

G00 Z#9 (RETIRADA FINAL DIRECTA AL PLANO SEGURO)

N999 (--- FIN DE MECANIZADO ---)
M09
M05
G28 G91 Z0.
G90
M30

(--- ALARMAS Y ERRORES ---)
N9001 #3000=1 (ERROR: FRESA MAYOR QUE EL DIAMETRO DE ROSCA)
N9002 #3000=2 (ERROR: PASO DE ROSCA DEBE SER MAYOR A CERO)
N9003 #3000=3 (ERROR: EL NUMERO DE VUELTAS DEBE SER MINIMO 1)
