O1002 (RANURA CIRCULAR HELICOIDAL)

(========================================)
(--- VARIABLES DE ENTRADA DEL OPERARIO ---)
#20 = 1     (NUMERO DE HERRAMIENTA)
(========================================)
#1 = 100.0 (DIAMETRO DE LA RANURA AL CENTRO DE LA HTA)
#2 = 12.0  (DIAMETRO DE LA HERRAMIENTA)
#3 = 15.0  (PROFUNDIDAD TOTAL Z FINAL - VALOR POSITIVO)
#4 = 2.0   (PROFUNDIDAD POR VUELTA EN Z - PITCH HELICOIDAL)
#5 = 120.0 (Vc - VELOCIDAD DE CORTE EN m/min)
#6 = 3.0   (NUMERO DE INSERTOS O LABIOS)
#7 = 0.08  (fz - AVANCE POR INSERTO EN mm/rev)
#8 = 50.0  (PLANO DE SEGURIDAD RETROCESO R)
#9 = 0.0   (CENTRO DE LA RANURA EN X)
#10 = 0.0  (CENTRO DE LA RANURA EN Y)
#14 = 0.0  (Z INICIAL DE CORTE)
(========================================)

(--- COMPROBACIONES DE SEGURIDAD ---)
IF [#1 LE 0] GOTO 9006
IF [#14 LE -#3] GOTO 9003

(--- PARAMETROS DE CORTE ---)
#100 = [#5 * 1000] / [3.1416 * #2] (RPM FIJAS)
#101 = #100 * #6 * #7 (AVANCE NOMINAL F LINEAL)

(--- GEOMETRIA DE TRAYECTORIA ---)
#102 = #1 / 2 (RADIO DE LA TRAYECTORIA DEL CENTRO DE LA HTA)
#104 = -#3 (Z FINAL EN COORDENADA NEGATIVA)
#106 = #14 (INICIALIZADOR DE PROFUNDIDAD Z ACTUAL)

(NOTA: EN ESTA OPERACION NO SE COMPENSA EL AVANCE PORQUE LA)
(HERRAMIENTA TRABAJA 100% EMBUTIDA ABRIENDO UNA RANURA DE SU MISMO ANCHO)

(--- CONFIGURACION INICIAL Y POSICIONAMIENTO ---)
T#20 M06 (LLAMAR HERRAMIENTA)
G90 G54 G17 G40 G80 G49
(MOVIMIENTO DIRECTO AL PUNTO DE INICIO SOBRE EL DIAMETRO DE LA RANURA)
G00 X[#9 + #102] Y#10 
G43 H#20 Z#8 (*** VERIFICAR CORRECTOR DE ALTURA H ***)
S#100 M03
M08

(BAJADA RAPIDA DE APROXIMACION A 1MM DEL Z INICIAL)
G00 Z[#14 + 1.0]
(BAJADA CONTROLADA AL Z INICIAL)
G01 Z#14 F[#101 / 2]

(--- BUCLE PRINCIPAL DE RAMPA HELICOIDAL ---)
WHILE [#106 GT #104] DO 1
    #106 = #106 - #4 (CALCULA LA PROFUNDIDAD AL FINAL DE ESTA VUELTA)
    
    (SI LA BAJADA CALCULA MAS ABAJO DEL FONDO, SE AJUSTA EXACTO AL FONDO)
    IF [#106 GE #104] GOTO 50
    #106 = #104 
    N50

    (INTERPOLACION HELICOIDAL: ARCO XY SIMULTANEO CON BAJADA EN Z)
    G03 I-[#102] J0. Z#106 F#101
END 1

(--- PASADA FINAL DE PLANICIDAD EN EL FONDO ---)
(ESTE CIRCULO EN Z FIJO ELIMINA LA RAMPA QUE QUEDA AL LLEGAR ABAJO)
G03 I-[#102] J0. F#101

(--- RETIRADA SEGURA ---)
(SE LEVANTA DIRECTAMENTE DESDE LA RANURA HACIA ARRIBA)
(NO SE MUEVE EN X NI EN Y PARA NO GOLPEAR EL NUCLEO CENTRAL)
G00 Z#8
M09
M05
G28 G91 Z0.
G90
M30

(--- ALARMAS ---)
N9003 #3000=3 (ERROR: Z INICIAL INFERIOR A Z FINAL)
N9006 #3000=6 (ERROR: DIAMETRO DE RANURA CERO O NEGATIVO)
